// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/client/catalog"
	"github.com/jenkins-x/anchore-client/client/image_tags"
	"github.com/jenkins-x/anchore-client/client/images"
	"github.com/jenkins-x/anchore-client/client/operations"
	"github.com/jenkins-x/anchore-client/client/policies"
	"github.com/jenkins-x/anchore-client/client/registries"
	"github.com/jenkins-x/anchore-client/client/subscriptions"
	"github.com/jenkins-x/anchore-client/client/system"
)

// Default anchore HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new anchore HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Anchore {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new anchore HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Anchore {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new anchore client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Anchore {
	cli := new(Anchore)
	cli.Transport = transport

	cli.Catalog = catalog.New(transport, formats)

	cli.ImageTags = image_tags.New(transport, formats)

	cli.Images = images.New(transport, formats)

	cli.Operations = operations.New(transport, formats)

	cli.Policies = policies.New(transport, formats)

	cli.Registries = registries.New(transport, formats)

	cli.Subscriptions = subscriptions.New(transport, formats)

	cli.System = system.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Anchore is a client for anchore
type Anchore struct {
	Catalog *catalog.Client

	ImageTags *image_tags.Client

	Images *images.Client

	Operations *operations.Client

	Policies *policies.Client

	Registries *registries.Client

	Subscriptions *subscriptions.Client

	System *system.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Anchore) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Catalog.SetTransport(transport)

	c.ImageTags.SetTransport(transport)

	c.Images.SetTransport(transport)

	c.Operations.SetTransport(transport)

	c.Policies.SetTransport(transport)

	c.Registries.SetTransport(transport)

	c.Subscriptions.SetTransport(transport)

	c.System.SetTransport(transport)

}
