// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// AddImageReader is a Reader for the AddImage structure.
type AddImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAddImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewAddImageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddImageOK creates a AddImageOK with default headers values
func NewAddImageOK() *AddImageOK {
	return &AddImageOK{}
}

/*AddImageOK handles this case with default header values.

Successfully added image to analysis queue
*/
type AddImageOK struct {
	Payload models.AddImageOKBody
}

func (o *AddImageOK) Error() string {
	return fmt.Sprintf("[POST /images][%d] addImageOK  %+v", 200, o.Payload)
}

func (o *AddImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddImageInternalServerError creates a AddImageInternalServerError with default headers values
func NewAddImageInternalServerError() *AddImageInternalServerError {
	return &AddImageInternalServerError{}
}

/*AddImageInternalServerError handles this case with default header values.

Internal Error
*/
type AddImageInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *AddImageInternalServerError) Error() string {
	return fmt.Sprintf("[POST /images][%d] addImageInternalServerError  %+v", 500, o.Payload)
}

func (o *AddImageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
