// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// DeleteImageByImageIDReader is a Reader for the DeleteImageByImageID structure.
type DeleteImageByImageIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteImageByImageIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteImageByImageIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewDeleteImageByImageIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteImageByImageIDOK creates a DeleteImageByImageIDOK with default headers values
func NewDeleteImageByImageIDOK() *DeleteImageByImageIDOK {
	return &DeleteImageByImageIDOK{}
}

/*DeleteImageByImageIDOK handles this case with default header values.

Image deletion success
*/
type DeleteImageByImageIDOK struct {
}

func (o *DeleteImageByImageIDOK) Error() string {
	return fmt.Sprintf("[DELETE /images/by_id/{imageId}][%d] deleteImageByImageIdOK ", 200)
}

func (o *DeleteImageByImageIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteImageByImageIDInternalServerError creates a DeleteImageByImageIDInternalServerError with default headers values
func NewDeleteImageByImageIDInternalServerError() *DeleteImageByImageIDInternalServerError {
	return &DeleteImageByImageIDInternalServerError{}
}

/*DeleteImageByImageIDInternalServerError handles this case with default header values.

Internal error
*/
type DeleteImageByImageIDInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *DeleteImageByImageIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /images/by_id/{imageId}][%d] deleteImageByImageIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteImageByImageIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
