// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// GetImageByImageIDReader is a Reader for the GetImageByImageID structure.
type GetImageByImageIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageByImageIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetImageByImageIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetImageByImageIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImageByImageIDOK creates a GetImageByImageIDOK with default headers values
func NewGetImageByImageIDOK() *GetImageByImageIDOK {
	return &GetImageByImageIDOK{}
}

/*GetImageByImageIDOK handles this case with default header values.

Image lookup success
*/
type GetImageByImageIDOK struct {
	Payload models.GetImageByImageIDOKBody
}

func (o *GetImageByImageIDOK) Error() string {
	return fmt.Sprintf("[GET /images/by_id/{imageId}][%d] getImageByImageIdOK  %+v", 200, o.Payload)
}

func (o *GetImageByImageIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImageByImageIDInternalServerError creates a GetImageByImageIDInternalServerError with default headers values
func NewGetImageByImageIDInternalServerError() *GetImageByImageIDInternalServerError {
	return &GetImageByImageIDInternalServerError{}
}

/*GetImageByImageIDInternalServerError handles this case with default header values.

Internal error
*/
type GetImageByImageIDInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetImageByImageIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /images/by_id/{imageId}][%d] getImageByImageIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetImageByImageIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
