// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// ImportImageReader is a Reader for the ImportImage structure.
type ImportImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewImportImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewImportImageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewImportImageOK creates a ImportImageOK with default headers values
func NewImportImageOK() *ImportImageOK {
	return &ImportImageOK{}
}

/*ImportImageOK handles this case with default header values.

Import task accepted
*/
type ImportImageOK struct {
	Payload models.ImportImageOKBody
}

func (o *ImportImageOK) Error() string {
	return fmt.Sprintf("[POST /imageimport][%d] importImageOK  %+v", 200, o.Payload)
}

func (o *ImportImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportImageInternalServerError creates a ImportImageInternalServerError with default headers values
func NewImportImageInternalServerError() *ImportImageInternalServerError {
	return &ImportImageInternalServerError{}
}

/*ImportImageInternalServerError handles this case with default header values.

Internal error
*/
type ImportImageInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *ImportImageInternalServerError) Error() string {
	return fmt.Sprintf("[POST /imageimport][%d] importImageInternalServerError  %+v", 500, o.Payload)
}

func (o *ImportImageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
