// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// GetSystemPruneCandidatesReader is a Reader for the GetSystemPruneCandidates structure.
type GetSystemPruneCandidatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemPruneCandidatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSystemPruneCandidatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetSystemPruneCandidatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemPruneCandidatesOK creates a GetSystemPruneCandidatesOK with default headers values
func NewGetSystemPruneCandidatesOK() *GetSystemPruneCandidatesOK {
	return &GetSystemPruneCandidatesOK{}
}

/*GetSystemPruneCandidatesOK handles this case with default header values.

success
*/
type GetSystemPruneCandidatesOK struct {
	Payload models.PruneCandidateList
}

func (o *GetSystemPruneCandidatesOK) Error() string {
	return fmt.Sprintf("[GET /system/prune/{resourcetype}][%d] getSystemPruneCandidatesOK  %+v", 200, o.Payload)
}

func (o *GetSystemPruneCandidatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSystemPruneCandidatesInternalServerError creates a GetSystemPruneCandidatesInternalServerError with default headers values
func NewGetSystemPruneCandidatesInternalServerError() *GetSystemPruneCandidatesInternalServerError {
	return &GetSystemPruneCandidatesInternalServerError{}
}

/*GetSystemPruneCandidatesInternalServerError handles this case with default header values.

Internal Error
*/
type GetSystemPruneCandidatesInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetSystemPruneCandidatesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /system/prune/{resourcetype}][%d] getSystemPruneCandidatesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSystemPruneCandidatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
