// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSystemPruneResourcetypesParams creates a new GetSystemPruneResourcetypesParams object
// with the default values initialized.
func NewGetSystemPruneResourcetypesParams() *GetSystemPruneResourcetypesParams {

	return &GetSystemPruneResourcetypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemPruneResourcetypesParamsWithTimeout creates a new GetSystemPruneResourcetypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSystemPruneResourcetypesParamsWithTimeout(timeout time.Duration) *GetSystemPruneResourcetypesParams {

	return &GetSystemPruneResourcetypesParams{

		timeout: timeout,
	}
}

// NewGetSystemPruneResourcetypesParamsWithContext creates a new GetSystemPruneResourcetypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSystemPruneResourcetypesParamsWithContext(ctx context.Context) *GetSystemPruneResourcetypesParams {

	return &GetSystemPruneResourcetypesParams{

		Context: ctx,
	}
}

// NewGetSystemPruneResourcetypesParamsWithHTTPClient creates a new GetSystemPruneResourcetypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSystemPruneResourcetypesParamsWithHTTPClient(client *http.Client) *GetSystemPruneResourcetypesParams {

	return &GetSystemPruneResourcetypesParams{
		HTTPClient: client,
	}
}

/*GetSystemPruneResourcetypesParams contains all the parameters to send to the API endpoint
for the get system prune resourcetypes operation typically these are written to a http.Request
*/
type GetSystemPruneResourcetypesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get system prune resourcetypes params
func (o *GetSystemPruneResourcetypesParams) WithTimeout(timeout time.Duration) *GetSystemPruneResourcetypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system prune resourcetypes params
func (o *GetSystemPruneResourcetypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system prune resourcetypes params
func (o *GetSystemPruneResourcetypesParams) WithContext(ctx context.Context) *GetSystemPruneResourcetypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system prune resourcetypes params
func (o *GetSystemPruneResourcetypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system prune resourcetypes params
func (o *GetSystemPruneResourcetypesParams) WithHTTPClient(client *http.Client) *GetSystemPruneResourcetypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system prune resourcetypes params
func (o *GetSystemPruneResourcetypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemPruneResourcetypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
