// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// GetSystemPruneResourcetypesReader is a Reader for the GetSystemPruneResourcetypes structure.
type GetSystemPruneResourcetypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemPruneResourcetypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSystemPruneResourcetypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetSystemPruneResourcetypesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemPruneResourcetypesOK creates a GetSystemPruneResourcetypesOK with default headers values
func NewGetSystemPruneResourcetypesOK() *GetSystemPruneResourcetypesOK {
	return &GetSystemPruneResourcetypesOK{}
}

/*GetSystemPruneResourcetypesOK handles this case with default header values.

success
*/
type GetSystemPruneResourcetypesOK struct {
	Payload []string
}

func (o *GetSystemPruneResourcetypesOK) Error() string {
	return fmt.Sprintf("[GET /system/prune][%d] getSystemPruneResourcetypesOK  %+v", 200, o.Payload)
}

func (o *GetSystemPruneResourcetypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSystemPruneResourcetypesInternalServerError creates a GetSystemPruneResourcetypesInternalServerError with default headers values
func NewGetSystemPruneResourcetypesInternalServerError() *GetSystemPruneResourcetypesInternalServerError {
	return &GetSystemPruneResourcetypesInternalServerError{}
}

/*GetSystemPruneResourcetypesInternalServerError handles this case with default header values.

Internal Error
*/
type GetSystemPruneResourcetypesInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetSystemPruneResourcetypesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /system/prune][%d] getSystemPruneResourcetypesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSystemPruneResourcetypesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
