// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// PostSystemPruneCandidatesReader is a Reader for the PostSystemPruneCandidates structure.
type PostSystemPruneCandidatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSystemPruneCandidatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostSystemPruneCandidatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewPostSystemPruneCandidatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSystemPruneCandidatesOK creates a PostSystemPruneCandidatesOK with default headers values
func NewPostSystemPruneCandidatesOK() *PostSystemPruneCandidatesOK {
	return &PostSystemPruneCandidatesOK{}
}

/*PostSystemPruneCandidatesOK handles this case with default header values.

success
*/
type PostSystemPruneCandidatesOK struct {
	Payload models.PruneCandidateList
}

func (o *PostSystemPruneCandidatesOK) Error() string {
	return fmt.Sprintf("[POST /system/prune/{resourcetype}][%d] postSystemPruneCandidatesOK  %+v", 200, o.Payload)
}

func (o *PostSystemPruneCandidatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSystemPruneCandidatesInternalServerError creates a PostSystemPruneCandidatesInternalServerError with default headers values
func NewPostSystemPruneCandidatesInternalServerError() *PostSystemPruneCandidatesInternalServerError {
	return &PostSystemPruneCandidatesInternalServerError{}
}

/*PostSystemPruneCandidatesInternalServerError handles this case with default header values.

Internal Error
*/
type PostSystemPruneCandidatesInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *PostSystemPruneCandidatesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /system/prune/{resourcetype}][%d] postSystemPruneCandidatesInternalServerError  %+v", 500, o.Payload)
}

func (o *PostSystemPruneCandidatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
