// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// DeleteSubscriptionReader is a Reader for the DeleteSubscription structure.
type DeleteSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewDeleteSubscriptionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSubscriptionOK creates a DeleteSubscriptionOK with default headers values
func NewDeleteSubscriptionOK() *DeleteSubscriptionOK {
	return &DeleteSubscriptionOK{}
}

/*DeleteSubscriptionOK handles this case with default header values.

Delete success
*/
type DeleteSubscriptionOK struct {
}

func (o *DeleteSubscriptionOK) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}][%d] deleteSubscriptionOK ", 200)
}

func (o *DeleteSubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubscriptionInternalServerError creates a DeleteSubscriptionInternalServerError with default headers values
func NewDeleteSubscriptionInternalServerError() *DeleteSubscriptionInternalServerError {
	return &DeleteSubscriptionInternalServerError{}
}

/*DeleteSubscriptionInternalServerError handles this case with default header values.

Internal Error
*/
type DeleteSubscriptionInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *DeleteSubscriptionInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}][%d] deleteSubscriptionInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteSubscriptionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
