// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// ListSubscriptionsReader is a Reader for the ListSubscriptions structure.
type ListSubscriptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSubscriptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListSubscriptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewListSubscriptionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListSubscriptionsOK creates a ListSubscriptionsOK with default headers values
func NewListSubscriptionsOK() *ListSubscriptionsOK {
	return &ListSubscriptionsOK{}
}

/*ListSubscriptionsOK handles this case with default header values.

Subscription listing
*/
type ListSubscriptionsOK struct {
	Payload models.SubscriptionList
}

func (o *ListSubscriptionsOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions][%d] listSubscriptionsOK  %+v", 200, o.Payload)
}

func (o *ListSubscriptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSubscriptionsInternalServerError creates a ListSubscriptionsInternalServerError with default headers values
func NewListSubscriptionsInternalServerError() *ListSubscriptionsInternalServerError {
	return &ListSubscriptionsInternalServerError{}
}

/*ListSubscriptionsInternalServerError handles this case with default header values.

Internal Error
*/
type ListSubscriptionsInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *ListSubscriptionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /subscriptions][%d] listSubscriptionsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListSubscriptionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
