// Code generated by go-swagger; DO NOT EDIT.

package image_tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new image tags API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for image tags API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ListImagetags lists all visible image digests and tags

List all image tags visible to the user
*/
func (a *Client) ListImagetags(params *ListImagetagsParams, authInfo runtime.ClientAuthInfoWriter) (*ListImagetagsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListImagetagsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "list_imagetags",
		Method:             "GET",
		PathPattern:        "/summaries/imagetags",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListImagetagsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListImagetagsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
