// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// NewAddPolicyParams creates a new AddPolicyParams object
// with the default values initialized.
func NewAddPolicyParams() *AddPolicyParams {
	var ()
	return &AddPolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddPolicyParamsWithTimeout creates a new AddPolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddPolicyParamsWithTimeout(timeout time.Duration) *AddPolicyParams {
	var ()
	return &AddPolicyParams{

		timeout: timeout,
	}
}

// NewAddPolicyParamsWithContext creates a new AddPolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddPolicyParamsWithContext(ctx context.Context) *AddPolicyParams {
	var ()
	return &AddPolicyParams{

		Context: ctx,
	}
}

// NewAddPolicyParamsWithHTTPClient creates a new AddPolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddPolicyParamsWithHTTPClient(client *http.Client) *AddPolicyParams {
	var ()
	return &AddPolicyParams{
		HTTPClient: client,
	}
}

/*AddPolicyParams contains all the parameters to send to the API endpoint
for the add policy operation typically these are written to a http.Request
*/
type AddPolicyParams struct {

	/*Bundle*/
	Bundle *models.PolicyBundle

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add policy params
func (o *AddPolicyParams) WithTimeout(timeout time.Duration) *AddPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add policy params
func (o *AddPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add policy params
func (o *AddPolicyParams) WithContext(ctx context.Context) *AddPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add policy params
func (o *AddPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add policy params
func (o *AddPolicyParams) WithHTTPClient(client *http.Client) *AddPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add policy params
func (o *AddPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBundle adds the bundle to the add policy params
func (o *AddPolicyParams) WithBundle(bundle *models.PolicyBundle) *AddPolicyParams {
	o.SetBundle(bundle)
	return o
}

// SetBundle adds the bundle to the add policy params
func (o *AddPolicyParams) SetBundle(bundle *models.PolicyBundle) {
	o.Bundle = bundle
}

// WriteToRequest writes these params to a swagger request
func (o *AddPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Bundle != nil {
		if err := r.SetBodyParam(o.Bundle); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
