// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListPoliciesParams creates a new ListPoliciesParams object
// with the default values initialized.
func NewListPoliciesParams() *ListPoliciesParams {
	var ()
	return &ListPoliciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListPoliciesParamsWithTimeout creates a new ListPoliciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListPoliciesParamsWithTimeout(timeout time.Duration) *ListPoliciesParams {
	var ()
	return &ListPoliciesParams{

		timeout: timeout,
	}
}

// NewListPoliciesParamsWithContext creates a new ListPoliciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListPoliciesParamsWithContext(ctx context.Context) *ListPoliciesParams {
	var ()
	return &ListPoliciesParams{

		Context: ctx,
	}
}

// NewListPoliciesParamsWithHTTPClient creates a new ListPoliciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListPoliciesParamsWithHTTPClient(client *http.Client) *ListPoliciesParams {
	var ()
	return &ListPoliciesParams{
		HTTPClient: client,
	}
}

/*ListPoliciesParams contains all the parameters to send to the API endpoint
for the list policies operation typically these are written to a http.Request
*/
type ListPoliciesParams struct {

	/*Detail
	  Include policy bundle detail in the form of the full bundle content for each entry

	*/
	Detail *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list policies params
func (o *ListPoliciesParams) WithTimeout(timeout time.Duration) *ListPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list policies params
func (o *ListPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list policies params
func (o *ListPoliciesParams) WithContext(ctx context.Context) *ListPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list policies params
func (o *ListPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list policies params
func (o *ListPoliciesParams) WithHTTPClient(client *http.Client) *ListPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list policies params
func (o *ListPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDetail adds the detail to the list policies params
func (o *ListPoliciesParams) WithDetail(detail *bool) *ListPoliciesParams {
	o.SetDetail(detail)
	return o
}

// SetDetail adds the detail to the list policies params
func (o *ListPoliciesParams) SetDetail(detail *bool) {
	o.Detail = detail
}

// WriteToRequest writes these params to a swagger request
func (o *ListPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Detail != nil {

		// query param detail
		var qrDetail bool
		if o.Detail != nil {
			qrDetail = *o.Detail
		}
		qDetail := swag.FormatBool(qrDetail)
		if qDetail != "" {
			if err := r.SetQueryParam("detail", qDetail); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
