// Code generated by go-swagger; DO NOT EDIT.

package registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// NewCreateRegistryParams creates a new CreateRegistryParams object
// with the default values initialized.
func NewCreateRegistryParams() *CreateRegistryParams {
	var ()
	return &CreateRegistryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRegistryParamsWithTimeout creates a new CreateRegistryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRegistryParamsWithTimeout(timeout time.Duration) *CreateRegistryParams {
	var ()
	return &CreateRegistryParams{

		timeout: timeout,
	}
}

// NewCreateRegistryParamsWithContext creates a new CreateRegistryParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRegistryParamsWithContext(ctx context.Context) *CreateRegistryParams {
	var ()
	return &CreateRegistryParams{

		Context: ctx,
	}
}

// NewCreateRegistryParamsWithHTTPClient creates a new CreateRegistryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRegistryParamsWithHTTPClient(client *http.Client) *CreateRegistryParams {
	var ()
	return &CreateRegistryParams{
		HTTPClient: client,
	}
}

/*CreateRegistryParams contains all the parameters to send to the API endpoint
for the create registry operation typically these are written to a http.Request
*/
type CreateRegistryParams struct {

	/*Registrydata*/
	Registrydata *models.RegistryConfiguration

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create registry params
func (o *CreateRegistryParams) WithTimeout(timeout time.Duration) *CreateRegistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create registry params
func (o *CreateRegistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create registry params
func (o *CreateRegistryParams) WithContext(ctx context.Context) *CreateRegistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create registry params
func (o *CreateRegistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create registry params
func (o *CreateRegistryParams) WithHTTPClient(client *http.Client) *CreateRegistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create registry params
func (o *CreateRegistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegistrydata adds the registrydata to the create registry params
func (o *CreateRegistryParams) WithRegistrydata(registrydata *models.RegistryConfiguration) *CreateRegistryParams {
	o.SetRegistrydata(registrydata)
	return o
}

// SetRegistrydata adds the registrydata to the create registry params
func (o *CreateRegistryParams) SetRegistrydata(registrydata *models.RegistryConfiguration) {
	o.Registrydata = registrydata
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRegistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Registrydata != nil {
		if err := r.SetBodyParam(o.Registrydata); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
