// Code generated by go-swagger; DO NOT EDIT.

package registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListRegistriesParams creates a new ListRegistriesParams object
// with the default values initialized.
func NewListRegistriesParams() *ListRegistriesParams {

	return &ListRegistriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListRegistriesParamsWithTimeout creates a new ListRegistriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListRegistriesParamsWithTimeout(timeout time.Duration) *ListRegistriesParams {

	return &ListRegistriesParams{

		timeout: timeout,
	}
}

// NewListRegistriesParamsWithContext creates a new ListRegistriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListRegistriesParamsWithContext(ctx context.Context) *ListRegistriesParams {

	return &ListRegistriesParams{

		Context: ctx,
	}
}

// NewListRegistriesParamsWithHTTPClient creates a new ListRegistriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListRegistriesParamsWithHTTPClient(client *http.Client) *ListRegistriesParams {

	return &ListRegistriesParams{
		HTTPClient: client,
	}
}

/*ListRegistriesParams contains all the parameters to send to the API endpoint
for the list registries operation typically these are written to a http.Request
*/
type ListRegistriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list registries params
func (o *ListRegistriesParams) WithTimeout(timeout time.Duration) *ListRegistriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list registries params
func (o *ListRegistriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list registries params
func (o *ListRegistriesParams) WithContext(ctx context.Context) *ListRegistriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list registries params
func (o *ListRegistriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list registries params
func (o *ListRegistriesParams) WithHTTPClient(client *http.Client) *ListRegistriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list registries params
func (o *ListRegistriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListRegistriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
