// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteServiceParams creates a new DeleteServiceParams object
// with the default values initialized.
func NewDeleteServiceParams() *DeleteServiceParams {
	var ()
	return &DeleteServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteServiceParamsWithTimeout creates a new DeleteServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteServiceParamsWithTimeout(timeout time.Duration) *DeleteServiceParams {
	var ()
	return &DeleteServiceParams{

		timeout: timeout,
	}
}

// NewDeleteServiceParamsWithContext creates a new DeleteServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteServiceParamsWithContext(ctx context.Context) *DeleteServiceParams {
	var ()
	return &DeleteServiceParams{

		Context: ctx,
	}
}

// NewDeleteServiceParamsWithHTTPClient creates a new DeleteServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteServiceParamsWithHTTPClient(client *http.Client) *DeleteServiceParams {
	var ()
	return &DeleteServiceParams{
		HTTPClient: client,
	}
}

/*DeleteServiceParams contains all the parameters to send to the API endpoint
for the delete service operation typically these are written to a http.Request
*/
type DeleteServiceParams struct {

	/*Hostid*/
	Hostid string
	/*Servicename*/
	Servicename string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete service params
func (o *DeleteServiceParams) WithTimeout(timeout time.Duration) *DeleteServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete service params
func (o *DeleteServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete service params
func (o *DeleteServiceParams) WithContext(ctx context.Context) *DeleteServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete service params
func (o *DeleteServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete service params
func (o *DeleteServiceParams) WithHTTPClient(client *http.Client) *DeleteServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete service params
func (o *DeleteServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHostid adds the hostid to the delete service params
func (o *DeleteServiceParams) WithHostid(hostid string) *DeleteServiceParams {
	o.SetHostid(hostid)
	return o
}

// SetHostid adds the hostid to the delete service params
func (o *DeleteServiceParams) SetHostid(hostid string) {
	o.Hostid = hostid
}

// WithServicename adds the servicename to the delete service params
func (o *DeleteServiceParams) WithServicename(servicename string) *DeleteServiceParams {
	o.SetServicename(servicename)
	return o
}

// SetServicename adds the servicename to the delete service params
func (o *DeleteServiceParams) SetServicename(servicename string) {
	o.Servicename = servicename
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hostid
	if err := r.SetPathParam("hostid", o.Hostid); err != nil {
		return err
	}

	// path param servicename
	if err := r.SetPathParam("servicename", o.Servicename); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
