// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// DescribePolicyReader is a Reader for the DescribePolicy structure.
type DescribePolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribePolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribePolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribePolicyOK creates a DescribePolicyOK with default headers values
func NewDescribePolicyOK() *DescribePolicyOK {
	return &DescribePolicyOK{}
}

/*DescribePolicyOK handles this case with default header values.

Policy Language Description
*/
type DescribePolicyOK struct {
	Payload models.DescribePolicyOKBody
}

func (o *DescribePolicyOK) Error() string {
	return fmt.Sprintf("[GET /system/policy_spec][%d] describePolicyOK  %+v", 200, o.Payload)
}

func (o *DescribePolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
