// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribePolicyParams creates a new DescribePolicyParams object
// with the default values initialized.
func NewDescribePolicyParams() *DescribePolicyParams {

	return &DescribePolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribePolicyParamsWithTimeout creates a new DescribePolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribePolicyParamsWithTimeout(timeout time.Duration) *DescribePolicyParams {

	return &DescribePolicyParams{

		timeout: timeout,
	}
}

// NewDescribePolicyParamsWithContext creates a new DescribePolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribePolicyParamsWithContext(ctx context.Context) *DescribePolicyParams {

	return &DescribePolicyParams{

		Context: ctx,
	}
}

// NewDescribePolicyParamsWithHTTPClient creates a new DescribePolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribePolicyParamsWithHTTPClient(client *http.Client) *DescribePolicyParams {

	return &DescribePolicyParams{
		HTTPClient: client,
	}
}

/*DescribePolicyParams contains all the parameters to send to the API endpoint
for the describe policy operation typically these are written to a http.Request
*/
type DescribePolicyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe policy params
func (o *DescribePolicyParams) WithTimeout(timeout time.Duration) *DescribePolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe policy params
func (o *DescribePolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe policy params
func (o *DescribePolicyParams) WithContext(ctx context.Context) *DescribePolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe policy params
func (o *DescribePolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe policy params
func (o *DescribePolicyParams) WithHTTPClient(client *http.Client) *DescribePolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe policy params
func (o *DescribePolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DescribePolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
