// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// GetImageVulnerabilitiesByTypeReader is a Reader for the GetImageVulnerabilitiesByType structure.
type GetImageVulnerabilitiesByTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageVulnerabilitiesByTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetImageVulnerabilitiesByTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetImageVulnerabilitiesByTypeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImageVulnerabilitiesByTypeOK creates a GetImageVulnerabilitiesByTypeOK with default headers values
func NewGetImageVulnerabilitiesByTypeOK() *GetImageVulnerabilitiesByTypeOK {
	return &GetImageVulnerabilitiesByTypeOK{}
}

/*GetImageVulnerabilitiesByTypeOK handles this case with default header values.

Vulnerability listing for the image
*/
type GetImageVulnerabilitiesByTypeOK struct {
	Payload models.VulnerabilityList
}

func (o *GetImageVulnerabilitiesByTypeOK) Error() string {
	return fmt.Sprintf("[GET /images/{imageDigest}/vuln/{vtype}][%d] getImageVulnerabilitiesByTypeOK  %+v", 200, o.Payload)
}

func (o *GetImageVulnerabilitiesByTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImageVulnerabilitiesByTypeInternalServerError creates a GetImageVulnerabilitiesByTypeInternalServerError with default headers values
func NewGetImageVulnerabilitiesByTypeInternalServerError() *GetImageVulnerabilitiesByTypeInternalServerError {
	return &GetImageVulnerabilitiesByTypeInternalServerError{}
}

/*GetImageVulnerabilitiesByTypeInternalServerError handles this case with default header values.

Internal Error
*/
type GetImageVulnerabilitiesByTypeInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetImageVulnerabilitiesByTypeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /images/{imageDigest}/vuln/{vtype}][%d] getImageVulnerabilitiesByTypeInternalServerError  %+v", 500, o.Payload)
}

func (o *GetImageVulnerabilitiesByTypeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
