// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetImageVulnerabilitiesByTypeParams creates a new GetImageVulnerabilitiesByTypeParams object
// with the default values initialized.
func NewGetImageVulnerabilitiesByTypeParams() *GetImageVulnerabilitiesByTypeParams {
	var ()
	return &GetImageVulnerabilitiesByTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageVulnerabilitiesByTypeParamsWithTimeout creates a new GetImageVulnerabilitiesByTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImageVulnerabilitiesByTypeParamsWithTimeout(timeout time.Duration) *GetImageVulnerabilitiesByTypeParams {
	var ()
	return &GetImageVulnerabilitiesByTypeParams{

		timeout: timeout,
	}
}

// NewGetImageVulnerabilitiesByTypeParamsWithContext creates a new GetImageVulnerabilitiesByTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetImageVulnerabilitiesByTypeParamsWithContext(ctx context.Context) *GetImageVulnerabilitiesByTypeParams {
	var ()
	return &GetImageVulnerabilitiesByTypeParams{

		Context: ctx,
	}
}

// NewGetImageVulnerabilitiesByTypeParamsWithHTTPClient creates a new GetImageVulnerabilitiesByTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetImageVulnerabilitiesByTypeParamsWithHTTPClient(client *http.Client) *GetImageVulnerabilitiesByTypeParams {
	var ()
	return &GetImageVulnerabilitiesByTypeParams{
		HTTPClient: client,
	}
}

/*GetImageVulnerabilitiesByTypeParams contains all the parameters to send to the API endpoint
for the get image vulnerabilities by type operation typically these are written to a http.Request
*/
type GetImageVulnerabilitiesByTypeParams struct {

	/*ImageDigest*/
	ImageDigest string
	/*Vtype*/
	Vtype string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) WithTimeout(timeout time.Duration) *GetImageVulnerabilitiesByTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) WithContext(ctx context.Context) *GetImageVulnerabilitiesByTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) WithHTTPClient(client *http.Client) *GetImageVulnerabilitiesByTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageDigest adds the imageDigest to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) WithImageDigest(imageDigest string) *GetImageVulnerabilitiesByTypeParams {
	o.SetImageDigest(imageDigest)
	return o
}

// SetImageDigest adds the imageDigest to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) SetImageDigest(imageDigest string) {
	o.ImageDigest = imageDigest
}

// WithVtype adds the vtype to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) WithVtype(vtype string) *GetImageVulnerabilitiesByTypeParams {
	o.SetVtype(vtype)
	return o
}

// SetVtype adds the vtype to the get image vulnerabilities by type params
func (o *GetImageVulnerabilitiesByTypeParams) SetVtype(vtype string) {
	o.Vtype = vtype
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageVulnerabilitiesByTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imageDigest
	if err := r.SetPathParam("imageDigest", o.ImageDigest); err != nil {
		return err
	}

	// path param vtype
	if err := r.SetPathParam("vtype", o.Vtype); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
