// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetImagePolicyCheckByImageIDParams creates a new GetImagePolicyCheckByImageIDParams object
// with the default values initialized.
func NewGetImagePolicyCheckByImageIDParams() *GetImagePolicyCheckByImageIDParams {
	var ()
	return &GetImagePolicyCheckByImageIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImagePolicyCheckByImageIDParamsWithTimeout creates a new GetImagePolicyCheckByImageIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImagePolicyCheckByImageIDParamsWithTimeout(timeout time.Duration) *GetImagePolicyCheckByImageIDParams {
	var ()
	return &GetImagePolicyCheckByImageIDParams{

		timeout: timeout,
	}
}

// NewGetImagePolicyCheckByImageIDParamsWithContext creates a new GetImagePolicyCheckByImageIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetImagePolicyCheckByImageIDParamsWithContext(ctx context.Context) *GetImagePolicyCheckByImageIDParams {
	var ()
	return &GetImagePolicyCheckByImageIDParams{

		Context: ctx,
	}
}

// NewGetImagePolicyCheckByImageIDParamsWithHTTPClient creates a new GetImagePolicyCheckByImageIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetImagePolicyCheckByImageIDParamsWithHTTPClient(client *http.Client) *GetImagePolicyCheckByImageIDParams {
	var ()
	return &GetImagePolicyCheckByImageIDParams{
		HTTPClient: client,
	}
}

/*GetImagePolicyCheckByImageIDParams contains all the parameters to send to the API endpoint
for the get image policy check by image Id operation typically these are written to a http.Request
*/
type GetImagePolicyCheckByImageIDParams struct {

	/*Detail*/
	Detail *bool
	/*History*/
	History *bool
	/*ImageID*/
	ImageID string
	/*PolicyID*/
	PolicyID *string
	/*Tag*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) WithTimeout(timeout time.Duration) *GetImagePolicyCheckByImageIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) WithContext(ctx context.Context) *GetImagePolicyCheckByImageIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) WithHTTPClient(client *http.Client) *GetImagePolicyCheckByImageIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDetail adds the detail to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) WithDetail(detail *bool) *GetImagePolicyCheckByImageIDParams {
	o.SetDetail(detail)
	return o
}

// SetDetail adds the detail to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) SetDetail(detail *bool) {
	o.Detail = detail
}

// WithHistory adds the history to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) WithHistory(history *bool) *GetImagePolicyCheckByImageIDParams {
	o.SetHistory(history)
	return o
}

// SetHistory adds the history to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) SetHistory(history *bool) {
	o.History = history
}

// WithImageID adds the imageID to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) WithImageID(imageID string) *GetImagePolicyCheckByImageIDParams {
	o.SetImageID(imageID)
	return o
}

// SetImageID adds the imageId to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) SetImageID(imageID string) {
	o.ImageID = imageID
}

// WithPolicyID adds the policyID to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) WithPolicyID(policyID *string) *GetImagePolicyCheckByImageIDParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) SetPolicyID(policyID *string) {
	o.PolicyID = policyID
}

// WithTag adds the tag to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) WithTag(tag string) *GetImagePolicyCheckByImageIDParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get image policy check by image Id params
func (o *GetImagePolicyCheckByImageIDParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetImagePolicyCheckByImageIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Detail != nil {

		// query param detail
		var qrDetail bool
		if o.Detail != nil {
			qrDetail = *o.Detail
		}
		qDetail := swag.FormatBool(qrDetail)
		if qDetail != "" {
			if err := r.SetQueryParam("detail", qDetail); err != nil {
				return err
			}
		}

	}

	if o.History != nil {

		// query param history
		var qrHistory bool
		if o.History != nil {
			qrHistory = *o.History
		}
		qHistory := swag.FormatBool(qrHistory)
		if qHistory != "" {
			if err := r.SetQueryParam("history", qHistory); err != nil {
				return err
			}
		}

	}

	// path param imageId
	if err := r.SetPathParam("imageId", o.ImageID); err != nil {
		return err
	}

	if o.PolicyID != nil {

		// query param policyId
		var qrPolicyID string
		if o.PolicyID != nil {
			qrPolicyID = *o.PolicyID
		}
		qPolicyID := qrPolicyID
		if qPolicyID != "" {
			if err := r.SetQueryParam("policyId", qPolicyID); err != nil {
				return err
			}
		}

	}

	// query param tag
	qrTag := o.Tag
	qTag := qrTag
	if qTag != "" {
		if err := r.SetQueryParam("tag", qTag); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
