// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// GetImageContentByTypeReader is a Reader for the GetImageContentByType structure.
type GetImageContentByTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageContentByTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetImageContentByTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetImageContentByTypeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImageContentByTypeOK creates a GetImageContentByTypeOK with default headers values
func NewGetImageContentByTypeOK() *GetImageContentByTypeOK {
	return &GetImageContentByTypeOK{}
}

/*GetImageContentByTypeOK handles this case with default header values.

Content of specified type from the image
*/
type GetImageContentByTypeOK struct {
	Payload *models.ContentResponse
}

func (o *GetImageContentByTypeOK) Error() string {
	return fmt.Sprintf("[GET /images/{imageDigest}/content/{ctype}][%d] getImageContentByTypeOK  %+v", 200, o.Payload)
}

func (o *GetImageContentByTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImageContentByTypeInternalServerError creates a GetImageContentByTypeInternalServerError with default headers values
func NewGetImageContentByTypeInternalServerError() *GetImageContentByTypeInternalServerError {
	return &GetImageContentByTypeInternalServerError{}
}

/*GetImageContentByTypeInternalServerError handles this case with default header values.

Internal error
*/
type GetImageContentByTypeInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetImageContentByTypeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /images/{imageDigest}/content/{ctype}][%d] getImageContentByTypeInternalServerError  %+v", 500, o.Payload)
}

func (o *GetImageContentByTypeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
