// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicesByNameAndHostParams creates a new GetServicesByNameAndHostParams object
// with the default values initialized.
func NewGetServicesByNameAndHostParams() *GetServicesByNameAndHostParams {
	var ()
	return &GetServicesByNameAndHostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicesByNameAndHostParamsWithTimeout creates a new GetServicesByNameAndHostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicesByNameAndHostParamsWithTimeout(timeout time.Duration) *GetServicesByNameAndHostParams {
	var ()
	return &GetServicesByNameAndHostParams{

		timeout: timeout,
	}
}

// NewGetServicesByNameAndHostParamsWithContext creates a new GetServicesByNameAndHostParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicesByNameAndHostParamsWithContext(ctx context.Context) *GetServicesByNameAndHostParams {
	var ()
	return &GetServicesByNameAndHostParams{

		Context: ctx,
	}
}

// NewGetServicesByNameAndHostParamsWithHTTPClient creates a new GetServicesByNameAndHostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServicesByNameAndHostParamsWithHTTPClient(client *http.Client) *GetServicesByNameAndHostParams {
	var ()
	return &GetServicesByNameAndHostParams{
		HTTPClient: client,
	}
}

/*GetServicesByNameAndHostParams contains all the parameters to send to the API endpoint
for the get services by name and host operation typically these are written to a http.Request
*/
type GetServicesByNameAndHostParams struct {

	/*Hostid*/
	Hostid string
	/*Servicename*/
	Servicename string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get services by name and host params
func (o *GetServicesByNameAndHostParams) WithTimeout(timeout time.Duration) *GetServicesByNameAndHostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get services by name and host params
func (o *GetServicesByNameAndHostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get services by name and host params
func (o *GetServicesByNameAndHostParams) WithContext(ctx context.Context) *GetServicesByNameAndHostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get services by name and host params
func (o *GetServicesByNameAndHostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get services by name and host params
func (o *GetServicesByNameAndHostParams) WithHTTPClient(client *http.Client) *GetServicesByNameAndHostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get services by name and host params
func (o *GetServicesByNameAndHostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHostid adds the hostid to the get services by name and host params
func (o *GetServicesByNameAndHostParams) WithHostid(hostid string) *GetServicesByNameAndHostParams {
	o.SetHostid(hostid)
	return o
}

// SetHostid adds the hostid to the get services by name and host params
func (o *GetServicesByNameAndHostParams) SetHostid(hostid string) {
	o.Hostid = hostid
}

// WithServicename adds the servicename to the get services by name and host params
func (o *GetServicesByNameAndHostParams) WithServicename(servicename string) *GetServicesByNameAndHostParams {
	o.SetServicename(servicename)
	return o
}

// SetServicename adds the servicename to the get services by name and host params
func (o *GetServicesByNameAndHostParams) SetServicename(servicename string) {
	o.Servicename = servicename
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicesByNameAndHostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hostid
	if err := r.SetPathParam("hostid", o.Hostid); err != nil {
		return err
	}

	// path param servicename
	if err := r.SetPathParam("servicename", o.Servicename); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
