// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetImageVulnerabilitiesByTypeImageIDParams creates a new GetImageVulnerabilitiesByTypeImageIDParams object
// with the default values initialized.
func NewGetImageVulnerabilitiesByTypeImageIDParams() *GetImageVulnerabilitiesByTypeImageIDParams {
	var ()
	return &GetImageVulnerabilitiesByTypeImageIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageVulnerabilitiesByTypeImageIDParamsWithTimeout creates a new GetImageVulnerabilitiesByTypeImageIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImageVulnerabilitiesByTypeImageIDParamsWithTimeout(timeout time.Duration) *GetImageVulnerabilitiesByTypeImageIDParams {
	var ()
	return &GetImageVulnerabilitiesByTypeImageIDParams{

		timeout: timeout,
	}
}

// NewGetImageVulnerabilitiesByTypeImageIDParamsWithContext creates a new GetImageVulnerabilitiesByTypeImageIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetImageVulnerabilitiesByTypeImageIDParamsWithContext(ctx context.Context) *GetImageVulnerabilitiesByTypeImageIDParams {
	var ()
	return &GetImageVulnerabilitiesByTypeImageIDParams{

		Context: ctx,
	}
}

// NewGetImageVulnerabilitiesByTypeImageIDParamsWithHTTPClient creates a new GetImageVulnerabilitiesByTypeImageIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetImageVulnerabilitiesByTypeImageIDParamsWithHTTPClient(client *http.Client) *GetImageVulnerabilitiesByTypeImageIDParams {
	var ()
	return &GetImageVulnerabilitiesByTypeImageIDParams{
		HTTPClient: client,
	}
}

/*GetImageVulnerabilitiesByTypeImageIDParams contains all the parameters to send to the API endpoint
for the get image vulnerabilities by type image Id operation typically these are written to a http.Request
*/
type GetImageVulnerabilitiesByTypeImageIDParams struct {

	/*ImageID*/
	ImageID string
	/*Vtype*/
	Vtype string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) WithTimeout(timeout time.Duration) *GetImageVulnerabilitiesByTypeImageIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) WithContext(ctx context.Context) *GetImageVulnerabilitiesByTypeImageIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) WithHTTPClient(client *http.Client) *GetImageVulnerabilitiesByTypeImageIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageID adds the imageID to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) WithImageID(imageID string) *GetImageVulnerabilitiesByTypeImageIDParams {
	o.SetImageID(imageID)
	return o
}

// SetImageID adds the imageId to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) SetImageID(imageID string) {
	o.ImageID = imageID
}

// WithVtype adds the vtype to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) WithVtype(vtype string) *GetImageVulnerabilitiesByTypeImageIDParams {
	o.SetVtype(vtype)
	return o
}

// SetVtype adds the vtype to the get image vulnerabilities by type image Id params
func (o *GetImageVulnerabilitiesByTypeImageIDParams) SetVtype(vtype string) {
	o.Vtype = vtype
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageVulnerabilitiesByTypeImageIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imageId
	if err := r.SetPathParam("imageId", o.ImageID); err != nil {
		return err
	}

	// path param vtype
	if err := r.SetPathParam("vtype", o.Vtype); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
