// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// GetImageVulnerabilitiesByTypeImageIDReader is a Reader for the GetImageVulnerabilitiesByTypeImageID structure.
type GetImageVulnerabilitiesByTypeImageIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageVulnerabilitiesByTypeImageIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetImageVulnerabilitiesByTypeImageIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetImageVulnerabilitiesByTypeImageIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImageVulnerabilitiesByTypeImageIDOK creates a GetImageVulnerabilitiesByTypeImageIDOK with default headers values
func NewGetImageVulnerabilitiesByTypeImageIDOK() *GetImageVulnerabilitiesByTypeImageIDOK {
	return &GetImageVulnerabilitiesByTypeImageIDOK{}
}

/*GetImageVulnerabilitiesByTypeImageIDOK handles this case with default header values.

Vulnerability listing for the image
*/
type GetImageVulnerabilitiesByTypeImageIDOK struct {
	Payload models.VulnerabilityList
}

func (o *GetImageVulnerabilitiesByTypeImageIDOK) Error() string {
	return fmt.Sprintf("[GET /images/by_id/{imageId}/vuln/{vtype}][%d] getImageVulnerabilitiesByTypeImageIdOK  %+v", 200, o.Payload)
}

func (o *GetImageVulnerabilitiesByTypeImageIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImageVulnerabilitiesByTypeImageIDInternalServerError creates a GetImageVulnerabilitiesByTypeImageIDInternalServerError with default headers values
func NewGetImageVulnerabilitiesByTypeImageIDInternalServerError() *GetImageVulnerabilitiesByTypeImageIDInternalServerError {
	return &GetImageVulnerabilitiesByTypeImageIDInternalServerError{}
}

/*GetImageVulnerabilitiesByTypeImageIDInternalServerError handles this case with default header values.

Internal Error
*/
type GetImageVulnerabilitiesByTypeImageIDInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetImageVulnerabilitiesByTypeImageIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /images/by_id/{imageId}/vuln/{vtype}][%d] getImageVulnerabilitiesByTypeImageIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetImageVulnerabilitiesByTypeImageIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
