// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// GetServicesByNameAndHostReader is a Reader for the GetServicesByNameAndHost structure.
type GetServicesByNameAndHostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServicesByNameAndHostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetServicesByNameAndHostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetServicesByNameAndHostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServicesByNameAndHostOK creates a GetServicesByNameAndHostOK with default headers values
func NewGetServicesByNameAndHostOK() *GetServicesByNameAndHostOK {
	return &GetServicesByNameAndHostOK{}
}

/*GetServicesByNameAndHostOK handles this case with default header values.

Listing of registered services
*/
type GetServicesByNameAndHostOK struct {
	Payload models.ServiceList
}

func (o *GetServicesByNameAndHostOK) Error() string {
	return fmt.Sprintf("[GET /system/services/{servicename}/{hostid}][%d] getServicesByNameAndHostOK  %+v", 200, o.Payload)
}

func (o *GetServicesByNameAndHostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServicesByNameAndHostInternalServerError creates a GetServicesByNameAndHostInternalServerError with default headers values
func NewGetServicesByNameAndHostInternalServerError() *GetServicesByNameAndHostInternalServerError {
	return &GetServicesByNameAndHostInternalServerError{}
}

/*GetServicesByNameAndHostInternalServerError handles this case with default header values.

Internal error
*/
type GetServicesByNameAndHostInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetServicesByNameAndHostInternalServerError) Error() string {
	return fmt.Sprintf("[GET /system/services/{servicename}/{hostid}][%d] getServicesByNameAndHostInternalServerError  %+v", 500, o.Payload)
}

func (o *GetServicesByNameAndHostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
