// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// GetImagePolicyCheckReader is a Reader for the GetImagePolicyCheck structure.
type GetImagePolicyCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImagePolicyCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetImagePolicyCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetImagePolicyCheckInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImagePolicyCheckOK creates a GetImagePolicyCheckOK with default headers values
func NewGetImagePolicyCheckOK() *GetImagePolicyCheckOK {
	return &GetImagePolicyCheckOK{}
}

/*GetImagePolicyCheckOK handles this case with default header values.

Policy evaluation success
*/
type GetImagePolicyCheckOK struct {
	Payload models.PolicyEvaluation
}

func (o *GetImagePolicyCheckOK) Error() string {
	return fmt.Sprintf("[GET /images/{imageDigest}/check][%d] getImagePolicyCheckOK  %+v", 200, o.Payload)
}

func (o *GetImagePolicyCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImagePolicyCheckInternalServerError creates a GetImagePolicyCheckInternalServerError with default headers values
func NewGetImagePolicyCheckInternalServerError() *GetImagePolicyCheckInternalServerError {
	return &GetImagePolicyCheckInternalServerError{}
}

/*GetImagePolicyCheckInternalServerError handles this case with default header values.

Internal Error
*/
type GetImagePolicyCheckInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetImagePolicyCheckInternalServerError) Error() string {
	return fmt.Sprintf("[GET /images/{imageDigest}/check][%d] getImagePolicyCheckInternalServerError  %+v", 500, o.Payload)
}

func (o *GetImagePolicyCheckInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
