// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jenkins-x/anchore-client/models"
)

// ListImageContentByImageidReader is a Reader for the ListImageContentByImageid structure.
type ListImageContentByImageidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListImageContentByImageidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListImageContentByImageidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewListImageContentByImageidInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListImageContentByImageidOK creates a ListImageContentByImageidOK with default headers values
func NewListImageContentByImageidOK() *ListImageContentByImageidOK {
	return &ListImageContentByImageidOK{}
}

/*ListImageContentByImageidOK handles this case with default header values.

Content of specified type from the image
*/
type ListImageContentByImageidOK struct {
	Payload []string
}

func (o *ListImageContentByImageidOK) Error() string {
	return fmt.Sprintf("[GET /images/by_id/{imageId}/content][%d] listImageContentByImageidOK  %+v", 200, o.Payload)
}

func (o *ListImageContentByImageidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListImageContentByImageidInternalServerError creates a ListImageContentByImageidInternalServerError with default headers values
func NewListImageContentByImageidInternalServerError() *ListImageContentByImageidInternalServerError {
	return &ListImageContentByImageidInternalServerError{}
}

/*ListImageContentByImageidInternalServerError handles this case with default header values.

Internal error
*/
type ListImageContentByImageidInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *ListImageContentByImageidInternalServerError) Error() string {
	return fmt.Sprintf("[GET /images/by_id/{imageId}/content][%d] listImageContentByImageidInternalServerError  %+v", 500, o.Payload)
}

func (o *ListImageContentByImageidInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
