// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListImageContentByImageidParams creates a new ListImageContentByImageidParams object
// with the default values initialized.
func NewListImageContentByImageidParams() *ListImageContentByImageidParams {
	var ()
	return &ListImageContentByImageidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListImageContentByImageidParamsWithTimeout creates a new ListImageContentByImageidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListImageContentByImageidParamsWithTimeout(timeout time.Duration) *ListImageContentByImageidParams {
	var ()
	return &ListImageContentByImageidParams{

		timeout: timeout,
	}
}

// NewListImageContentByImageidParamsWithContext creates a new ListImageContentByImageidParams object
// with the default values initialized, and the ability to set a context for a request
func NewListImageContentByImageidParamsWithContext(ctx context.Context) *ListImageContentByImageidParams {
	var ()
	return &ListImageContentByImageidParams{

		Context: ctx,
	}
}

// NewListImageContentByImageidParamsWithHTTPClient creates a new ListImageContentByImageidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListImageContentByImageidParamsWithHTTPClient(client *http.Client) *ListImageContentByImageidParams {
	var ()
	return &ListImageContentByImageidParams{
		HTTPClient: client,
	}
}

/*ListImageContentByImageidParams contains all the parameters to send to the API endpoint
for the list image content by imageid operation typically these are written to a http.Request
*/
type ListImageContentByImageidParams struct {

	/*ImageID*/
	ImageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list image content by imageid params
func (o *ListImageContentByImageidParams) WithTimeout(timeout time.Duration) *ListImageContentByImageidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list image content by imageid params
func (o *ListImageContentByImageidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list image content by imageid params
func (o *ListImageContentByImageidParams) WithContext(ctx context.Context) *ListImageContentByImageidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list image content by imageid params
func (o *ListImageContentByImageidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list image content by imageid params
func (o *ListImageContentByImageidParams) WithHTTPClient(client *http.Client) *ListImageContentByImageidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list image content by imageid params
func (o *ListImageContentByImageidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageID adds the imageID to the list image content by imageid params
func (o *ListImageContentByImageidParams) WithImageID(imageID string) *ListImageContentByImageidParams {
	o.SetImageID(imageID)
	return o
}

// SetImageID adds the imageId to the list image content by imageid params
func (o *ListImageContentByImageidParams) SetImageID(imageID string) {
	o.ImageID = imageID
}

// WriteToRequest writes these params to a swagger request
func (o *ListImageContentByImageidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imageId
	if err := r.SetPathParam("imageId", o.ImageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
