// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListImageContentParams creates a new ListImageContentParams object
// with the default values initialized.
func NewListImageContentParams() *ListImageContentParams {
	var ()
	return &ListImageContentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListImageContentParamsWithTimeout creates a new ListImageContentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListImageContentParamsWithTimeout(timeout time.Duration) *ListImageContentParams {
	var ()
	return &ListImageContentParams{

		timeout: timeout,
	}
}

// NewListImageContentParamsWithContext creates a new ListImageContentParams object
// with the default values initialized, and the ability to set a context for a request
func NewListImageContentParamsWithContext(ctx context.Context) *ListImageContentParams {
	var ()
	return &ListImageContentParams{

		Context: ctx,
	}
}

// NewListImageContentParamsWithHTTPClient creates a new ListImageContentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListImageContentParamsWithHTTPClient(client *http.Client) *ListImageContentParams {
	var ()
	return &ListImageContentParams{
		HTTPClient: client,
	}
}

/*ListImageContentParams contains all the parameters to send to the API endpoint
for the list image content operation typically these are written to a http.Request
*/
type ListImageContentParams struct {

	/*ImageDigest*/
	ImageDigest string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list image content params
func (o *ListImageContentParams) WithTimeout(timeout time.Duration) *ListImageContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list image content params
func (o *ListImageContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list image content params
func (o *ListImageContentParams) WithContext(ctx context.Context) *ListImageContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list image content params
func (o *ListImageContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list image content params
func (o *ListImageContentParams) WithHTTPClient(client *http.Client) *ListImageContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list image content params
func (o *ListImageContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageDigest adds the imageDigest to the list image content params
func (o *ListImageContentParams) WithImageDigest(imageDigest string) *ListImageContentParams {
	o.SetImageDigest(imageDigest)
	return o
}

// SetImageDigest adds the imageDigest to the list image content params
func (o *ListImageContentParams) SetImageDigest(imageDigest string) {
	o.ImageDigest = imageDigest
}

// WriteToRequest writes these params to a swagger request
func (o *ListImageContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imageDigest
	if err := r.SetPathParam("imageDigest", o.ImageDigest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
