// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AnchoreImageTagSummary A unique image in the engine.
// swagger:model AnchoreImageTagSummary
type AnchoreImageTagSummary struct {

	// analysis status
	AnalysisStatus string `json:"analysis_status,omitempty"`

	// created at
	CreatedAt int64 `json:"created_at,omitempty"`

	// fulltag
	Fulltag string `json:"fulltag,omitempty"`

	// image digest
	ImageDigest string `json:"imageDigest,omitempty"`

	// image Id
	ImageID string `json:"imageId,omitempty"`
}

// Validate validates this anchore image tag summary
func (m *AnchoreImageTagSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AnchoreImageTagSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AnchoreImageTagSummary) UnmarshalBinary(b []byte) error {
	var res AnchoreImageTagSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
