// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContentResponse Generic wrapper for content listings from images
// swagger:model ContentResponse
type ContentResponse struct {

	// content
	Content []interface{} `json:"content"`

	// content type
	ContentType string `json:"content_type,omitempty"`

	// image digest
	ImageDigest string `json:"imageDigest,omitempty"`
}

// Validate validates this content response
func (m *ContentResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContentResponse) validateContent(formats strfmt.Registry) error {

	if swag.IsZero(m.Content) { // not required
		return nil
	}

	for i := 0; i < len(m.Content); i++ {

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContentResponse) UnmarshalBinary(b []byte) error {
	var res ContentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
