// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GateSpec A description of the set of gates available in this engine and the triggers and parameters supported
// swagger:model GateSpec
type GateSpec struct {

	// Description of the gate
	Description string `json:"description,omitempty"`

	// Gate name, as it would appear in a policy document
	Name string `json:"name,omitempty"`

	// triggers
	Triggers GateSpecTriggers `json:"triggers"`
}

// Validate validates this gate spec
func (m *GateSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GateSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GateSpec) UnmarshalBinary(b []byte) error {
	var res GateSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
