// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImageDetail A metadata detail record for a specific image. Multiple detail records may map a single catalog image.
// swagger:model ImageDetail
type ImageDetail struct {

	// created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// dockerfile
	Dockerfile string `json:"dockerfile,omitempty"`

	// Full docker-pullable digest string including the registry url and repository necessary get the image
	FullDigest string `json:"fullDigest,omitempty"`

	// Full docker-pullalbe tag string referencing the image
	Fulltag string `json:"fulltag,omitempty"`

	// The parent Anchore Image record to which this detail maps
	ImageDigest string `json:"imageDigest,omitempty"`

	// image Id
	ImageID string `json:"imageId,omitempty"`

	// last updated
	LastUpdated strfmt.DateTime `json:"last_updated,omitempty"`

	// registry
	Registry string `json:"registry,omitempty"`

	// repo
	Repo string `json:"repo,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this image detail
func (m *ImageDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ImageDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageDetail) UnmarshalBinary(b []byte) error {
	var res ImageDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
