// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ImageContent A metadata content record for a specific image, containing different content type entries
// swagger:model ImageContent
type ImageContent interface{}
