// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RegistryConfiguration A registry entry describing the endpoint and credentials for a registry to pull images from
// swagger:model RegistryConfiguration
type RegistryConfiguration struct {

	// created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// last upated
	LastUpated strfmt.DateTime `json:"last_upated,omitempty"`

	// hostname:port string for accessing the registry, as would be used in a docker pull operation
	Registry string `json:"registry,omitempty"`

	// Type of registry
	RegistryType string `json:"registry_type,omitempty"`

	// Username portion of credential to use for this registry
	RegistryUser string `json:"registry_user,omitempty"`

	// Use TLS/SSL verification for the registry URL
	RegistryVerify bool `json:"registry_verify,omitempty"`

	// Engine user that owns this registry entry
	UserID string `json:"userId,omitempty"`
}

// Validate validates this registry configuration
func (m *RegistryConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RegistryConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistryConfiguration) UnmarshalBinary(b []byte) error {
	var res RegistryConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
