// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubscriptionRequest A subscription entry to add to the system
// swagger:model SubscriptionRequest
type SubscriptionRequest struct {

	// subscription key
	SubscriptionKey string `json:"subscription_key,omitempty"`

	// subscription type
	SubscriptionType string `json:"subscription_type,omitempty"`

	// subscription value
	SubscriptionValue string `json:"subscription_value,omitempty"`
}

// Validate validates this subscription request
func (m *SubscriptionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var subscriptionRequestTypeSubscriptionTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["policy_eval","tag_update","vuln_update","repo_update"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		subscriptionRequestTypeSubscriptionTypePropEnum = append(subscriptionRequestTypeSubscriptionTypePropEnum, v)
	}
}

const (
	// SubscriptionRequestSubscriptionTypePolicyEval captures enum value "policy_eval"
	SubscriptionRequestSubscriptionTypePolicyEval string = "policy_eval"
	// SubscriptionRequestSubscriptionTypeTagUpdate captures enum value "tag_update"
	SubscriptionRequestSubscriptionTypeTagUpdate string = "tag_update"
	// SubscriptionRequestSubscriptionTypeVulnUpdate captures enum value "vuln_update"
	SubscriptionRequestSubscriptionTypeVulnUpdate string = "vuln_update"
	// SubscriptionRequestSubscriptionTypeRepoUpdate captures enum value "repo_update"
	SubscriptionRequestSubscriptionTypeRepoUpdate string = "repo_update"
)

// prop value enum
func (m *SubscriptionRequest) validateSubscriptionTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, subscriptionRequestTypeSubscriptionTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SubscriptionRequest) validateSubscriptionType(formats strfmt.Registry) error {

	if swag.IsZero(m.SubscriptionType) { // not required
		return nil
	}

	// value enum
	if err := m.validateSubscriptionTypeEnum("subscription_type", "body", m.SubscriptionType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SubscriptionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriptionRequest) UnmarshalBinary(b []byte) error {
	var res SubscriptionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
