// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SubscriptionUpdate A modification to a subscription entry to change its status or value
// swagger:model SubscriptionUpdate
type SubscriptionUpdate struct {

	// Toggle the subscription processing on or off
	Active bool `json:"active,omitempty"`

	// The new subscription value, e.g. the new tag to be subscribed to
	SubscriptionValue string `json:"subscription_value,omitempty"`
}

// Validate validates this subscription update
func (m *SubscriptionUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SubscriptionUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriptionUpdate) UnmarshalBinary(b []byte) error {
	var res SubscriptionUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
