// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TriggerSpec Definition of a trigger and its parameters
// swagger:model TriggerSpec
type TriggerSpec struct {

	// Trigger description for what it tests and when it will fire during evaluation
	Description string `json:"description,omitempty"`

	// Name of the trigger as it would appear in a policy document
	Name string `json:"name,omitempty"`

	// parameters
	Parameters TriggerSpecParameters `json:"parameters"`
}

// Validate validates this trigger spec
func (m *TriggerSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TriggerSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TriggerSpec) UnmarshalBinary(b []byte) error {
	var res TriggerSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
